version: 2
updates:
  - package-ecosystem: pip
    directory: /user-service
    schedule: {interval: weekly}
  - package-ecosystem: pip
    directory: /product-service
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /user-service
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directory: /product-service
    schedule: {interval: weekly}
  - package-ecosystem: docker-compose
    directory: /
    schedule: {interval: weekly}
